# Generated by Django 4.1.3 on 2023-02-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="get_notification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="premium_account",
            field=models.BooleanField(default=False),
        ),
    ]
