name: Codestyle and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  codestyle:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
  test:
    needs: codestyle
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      DJANGO_ALLOWED_HOSTS: '*'
      USE_POSTGRES_DB: True
      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: True
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Start containers
        run: docker-compose up --build -d
      
      - name: Run tests
        run: docker-compose exec web pytest -vs app/tests/tests.py users/tests/tests.py

      - name: Stop containers
        run: docker-compose down
